-- =====================================================
-- Gold Layer Tables (Star Schema)
-- =====================================================

USE SCHEMA GOLD;

-- =============== DIMENSIONS ===============

-- DIM_EMPLOYEES (SCD Type 2)
CREATE TABLE IF NOT EXISTS DIM_EMPLOYEES (
    EMPLOYEE_SK INT AUTOINCREMENT PRIMARY KEY,
    EMPLOYEE_ID VARCHAR(100) NOT NULL,
    EMPLOYEE_CODE VARCHAR(50),
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    FULL_NAME VARCHAR(200),
    EMAIL VARCHAR(200),
    PHONE VARCHAR(50),
    JOB_TITLE VARCHAR(200),
    DEPARTMENT VARCHAR(100),
    STATUS VARCHAR(50),
    IS_ACTIVE BOOLEAN,
    HIRE_DATE TIMESTAMP_NTZ,
    VALID_FROM TIMESTAMP_NTZ NOT NULL,
    VALID_TO TIMESTAMP_NTZ,
    IS_CURRENT BOOLEAN NOT NULL DEFAULT TRUE
) COMMENT = 'Employee dimension with SCD Type 2';

-- DIM_PROJECTS (SCD Type 2)
CREATE TABLE IF NOT EXISTS DIM_PROJECTS (
    PROJECT_SK INT AUTOINCREMENT PRIMARY KEY,
    PROJECT_ID VARCHAR(100) NOT NULL,
    PROJECT_CODE VARCHAR(50),
    PROJECT_NAME VARCHAR(200),
    STATUS VARCHAR(50),
    IS_ACTIVE BOOLEAN,
    CLIENT_ID VARCHAR(100),
    CLIENT_NAME VARCHAR(200),
    VALID_FROM TIMESTAMP_NTZ NOT NULL,
    VALID_TO TIMESTAMP_NTZ,
    IS_CURRENT BOOLEAN NOT NULL DEFAULT TRUE
) COMMENT = 'Project dimension with SCD Type 2';

-- DIM_CLIENTS (SCD Type 2)
CREATE TABLE IF NOT EXISTS DIM_CLIENTS (
    CLIENT_SK INT AUTOINCREMENT PRIMARY KEY,
    CLIENT_ID VARCHAR(100) NOT NULL,
    CLIENT_CODE VARCHAR(50),
    CLIENT_NAME VARCHAR(200),
    INDUSTRY VARCHAR(100),
    STATUS VARCHAR(50),
    IS_ACTIVE BOOLEAN,
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    COUNTRY VARCHAR(100),
    VALID_FROM TIMESTAMP_NTZ NOT NULL,
    VALID_TO TIMESTAMP_NTZ,
    IS_CURRENT BOOLEAN NOT NULL DEFAULT TRUE
) COMMENT = 'Client dimension with SCD Type 2';

-- DIM_VENDORS (SCD Type 2)
CREATE TABLE IF NOT EXISTS DIM_VENDORS (
    VENDOR_SK INT AUTOINCREMENT PRIMARY KEY,
    VENDOR_ID VARCHAR(100) NOT NULL,
    VENDOR_CODE VARCHAR(50),
    VENDOR_NAME VARCHAR(200),
    VENDOR_TYPE VARCHAR(100),
    STATUS VARCHAR(50),
    IS_ACTIVE BOOLEAN,
    VALID_FROM TIMESTAMP_NTZ NOT NULL,
    VALID_TO TIMESTAMP_NTZ,
    IS_CURRENT BOOLEAN NOT NULL DEFAULT TRUE
) COMMENT = 'Vendor dimension with SCD Type 2';

-- DIM_DATE
CREATE TABLE IF NOT EXISTS DIM_DATE (
    DATE_SK INT PRIMARY KEY,
    DATE DATE NOT NULL UNIQUE,
    YEAR INT NOT NULL,
    QUARTER INT NOT NULL,
    MONTH INT NOT NULL,
    MONTH_NAME VARCHAR(20) NOT NULL,
    DAY INT NOT NULL,
    DAY_OF_WEEK INT NOT NULL,
    DAY_NAME VARCHAR(20) NOT NULL,
    DAY_OF_YEAR INT NOT NULL,
    WEEK_OF_YEAR INT NOT NULL,
    IS_WEEKEND BOOLEAN NOT NULL
) COMMENT = 'Date dimension (2020-2025)';

-- =============== FACTS ===============

-- FACT_PLACEMENTS
CREATE TABLE IF NOT EXISTS FACT_PLACEMENTS (
    PLACEMENT_SK INT AUTOINCREMENT PRIMARY KEY,
    EMPLOYEE_SK INT,
    PROJECT_SK INT,
    CLIENT_SK INT,
    START_DATE_SK INT,
    END_DATE_SK INT,
    PLACEMENT_ID VARCHAR(100) NOT NULL,
    PLACEMENT_CODE VARCHAR(50),
    STATUS VARCHAR(50),
    BILL_RATE FLOAT,
    PAY_RATE FLOAT,
    MARGIN FLOAT,
    MARGIN_PCT FLOAT,
    DURATION_DAYS INT,
    START_DATE DATE,
    END_DATE DATE,
    CREATED_AT TIMESTAMP_NTZ,
    FOREIGN KEY (EMPLOYEE_SK) REFERENCES DIM_EMPLOYEES(EMPLOYEE_SK),
    FOREIGN KEY (PROJECT_SK) REFERENCES DIM_PROJECTS(PROJECT_SK),
    FOREIGN KEY (CLIENT_SK) REFERENCES DIM_CLIENTS(CLIENT_SK),
    FOREIGN KEY (START_DATE_SK) REFERENCES DIM_DATE(DATE_SK),
    FOREIGN KEY (END_DATE_SK) REFERENCES DIM_DATE(DATE_SK)
) COMMENT = 'Placement fact table';

-- FACT_EXPENSES
CREATE TABLE IF NOT EXISTS FACT_EXPENSES (
    EXPENSE_SK INT AUTOINCREMENT PRIMARY KEY,
    EMPLOYEE_SK INT,
    PROJECT_SK INT,
    EXPENSE_DATE_SK INT,
    EXPENSE_ID VARCHAR(100) NOT NULL,
    EXPENSE_CODE VARCHAR(50),
    EXPENSE_TYPE VARCHAR(100),
    CATEGORY VARCHAR(100),
    STATUS VARCHAR(50),
    AMOUNT FLOAT,
    CURRENCY VARCHAR(10),
    IS_APPROVED BOOLEAN,
    IS_REIMBURSED BOOLEAN,
    EXPENSE_DATE DATE,
    CREATED_AT TIMESTAMP_NTZ,
    FOREIGN KEY (EMPLOYEE_SK) REFERENCES DIM_EMPLOYEES(EMPLOYEE_SK),
    FOREIGN KEY (PROJECT_SK) REFERENCES DIM_PROJECTS(PROJECT_SK),
    FOREIGN KEY (EXPENSE_DATE_SK) REFERENCES DIM_DATE(DATE_SK)
) COMMENT = 'Expense fact table';

-- FACT_INVOICES
CREATE TABLE IF NOT EXISTS FACT_INVOICES (
    INVOICE_SK INT AUTOINCREMENT PRIMARY KEY,
    CLIENT_SK INT,
    PROJECT_SK INT,
    INVOICE_DATE_SK INT,
    DUE_DATE_SK INT,
    INVOICE_ID VARCHAR(100) NOT NULL,
    INVOICE_NUMBER VARCHAR(100),
    STATUS VARCHAR(50),
    SUBTOTAL FLOAT,
    TAX FLOAT,
    TOTAL_AMOUNT FLOAT,
    CURRENCY VARCHAR(10),
    IS_PAID BOOLEAN,
    IS_OVERDUE BOOLEAN,
    INVOICE_DATE DATE,
    DUE_DATE DATE,
    PAYMENT_DATE DATE,
    CREATED_AT TIMESTAMP_NTZ,
    FOREIGN KEY (CLIENT_SK) REFERENCES DIM_CLIENTS(CLIENT_SK),
    FOREIGN KEY (PROJECT_SK) REFERENCES DIM_PROJECTS(PROJECT_SK),
    FOREIGN KEY (INVOICE_DATE_SK) REFERENCES DIM_DATE(DATE_SK),
    FOREIGN KEY (DUE_DATE_SK) REFERENCES DIM_DATE(DATE_SK)
) COMMENT = 'Invoice fact table';

-- Show all Gold tables
SHOW TABLES IN SCHEMA GOLD;
