-- =====================================================
-- Bronze (RAW) Layer Tables
-- =====================================================
-- Bronze tables store raw JSON data from CEIPAL API
-- Schema: ID (PK), DATA (VARIANT), RECORD_HASH, LOADED_AT

USE SCHEMA RAW;

-- Employees
CREATE TABLE IF NOT EXISTS CEIPAL_EMPLOYEES_BRONZE (
    ID VARCHAR(100) NOT NULL,
    DATA VARIANT NOT NULL,
    RECORD_HASH VARCHAR(64) NOT NULL,
    LOADED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ID, RECORD_HASH)
) COMMENT = 'Raw employee data from CEIPAL API';

-- Projects
CREATE TABLE IF NOT EXISTS CEIPAL_PROJECTS_BRONZE (
    ID VARCHAR(100) NOT NULL,
    DATA VARIANT NOT NULL,
    RECORD_HASH VARCHAR(64) NOT NULL,
    LOADED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ID, RECORD_HASH)
) COMMENT = 'Raw project data from CEIPAL API';

-- Placements
CREATE TABLE IF NOT EXISTS CEIPAL_PLACEMENTS_BRONZE (
    ID VARCHAR(100) NOT NULL,
    DATA VARIANT NOT NULL,
    RECORD_HASH VARCHAR(64) NOT NULL,
    LOADED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ID, RECORD_HASH)
) COMMENT = 'Raw placement data from CEIPAL API';

-- Clients
CREATE TABLE IF NOT EXISTS CEIPAL_CLIENTS_BRONZE (
    ID VARCHAR(100) NOT NULL,
    DATA VARIANT NOT NULL,
    RECORD_HASH VARCHAR(64) NOT NULL,
    LOADED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ID, RECORD_HASH)
) COMMENT = 'Raw client data from CEIPAL API';

-- Vendors
CREATE TABLE IF NOT EXISTS CEIPAL_VENDORS_BRONZE (
    ID VARCHAR(100) NOT NULL,
    DATA VARIANT NOT NULL,
    RECORD_HASH VARCHAR(64) NOT NULL,
    LOADED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ID, RECORD_HASH)
) COMMENT = 'Raw vendor data from CEIPAL API';

-- Expenses
CREATE TABLE IF NOT EXISTS CEIPAL_EXPENSES_BRONZE (
    ID VARCHAR(100) NOT NULL,
    DATA VARIANT NOT NULL,
    RECORD_HASH VARCHAR(64) NOT NULL,
    LOADED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ID, RECORD_HASH)
) COMMENT = 'Raw expense data from CEIPAL API';

-- Invoices
CREATE TABLE IF NOT EXISTS CEIPAL_INVOICES_BRONZE (
    ID VARCHAR(100) NOT NULL,
    DATA VARIANT NOT NULL,
    RECORD_HASH VARCHAR(64) NOT NULL,
    LOADED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ID, RECORD_HASH)
) COMMENT = 'Raw invoice data from CEIPAL API';

-- Show all Bronze tables
SHOW TABLES IN SCHEMA RAW;
