-- =====================================================
-- All Silver Layer Tables
-- =====================================================

USE SCHEMA SILVER;

-- EMPLOYEES
CREATE TABLE IF NOT EXISTS CEIPAL_EMPLOYEES (
    ID VARCHAR(100) NOT NULL PRIMARY KEY,
    EMPLOYEE_CODE VARCHAR(50),
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    FULL_NAME VARCHAR(200),
    EMAIL VARCHAR(200),
    PHONE VARCHAR(50),
    JOB_TITLE VARCHAR(200),
    DEPARTMENT VARCHAR(100),
    STATUS VARCHAR(50),
    IS_ACTIVE BOOLEAN,
    HIRE_DATE TIMESTAMP_NTZ,
    SILVER_PROCESSED_AT TIMESTAMP_NTZ,
    SILVER_IS_CURRENT BOOLEAN
) COMMENT = 'Cleaned employee data';

-- PROJECTS
CREATE TABLE IF NOT EXISTS CEIPAL_PROJECTS (
    ID VARCHAR(100) NOT NULL PRIMARY KEY,
    PROJECT_CODE VARCHAR(50),
    PROJECT_NAME VARCHAR(200),
    STATUS VARCHAR(50),
    IS_ACTIVE BOOLEAN,
    CLIENT_ID VARCHAR(100),
    CLIENT_NAME VARCHAR(200),
    START_DATE TIMESTAMP_NTZ,
    END_DATE TIMESTAMP_NTZ,
    BUDGET FLOAT,
    CURRENCY VARCHAR(10),
    SILVER_PROCESSED_AT TIMESTAMP_NTZ,
    SILVER_IS_CURRENT BOOLEAN
) COMMENT = 'Cleaned project data';

-- PLACEMENTS
CREATE TABLE IF NOT EXISTS CEIPAL_PLACEMENTS (
    ID VARCHAR(100) NOT NULL PRIMARY KEY,
    PLACEMENT_CODE VARCHAR(50),
    EMPLOYEE_ID VARCHAR(100),
    EMPLOYEE_NAME VARCHAR(200),
    PROJECT_ID VARCHAR(100),
    PROJECT_NAME VARCHAR(200),
    CLIENT_ID VARCHAR(100),
    CLIENT_NAME VARCHAR(200),
    STATUS VARCHAR(50),
    IS_ACTIVE BOOLEAN,
    START_DATE TIMESTAMP_NTZ,
    END_DATE TIMESTAMP_NTZ,
    BILL_RATE FLOAT,
    PAY_RATE FLOAT,
    MARGIN FLOAT,
    MARGIN_PCT FLOAT,
    DURATION_DAYS INT,
    CURRENCY VARCHAR(10),
    SILVER_PROCESSED_AT TIMESTAMP_NTZ,
    SILVER_IS_CURRENT BOOLEAN
) COMMENT = 'Cleaned placement data';

-- CLIENTS
CREATE TABLE IF NOT EXISTS CEIPAL_CLIENTS (
    ID VARCHAR(100) NOT NULL PRIMARY KEY,
    CLIENT_CODE VARCHAR(50),
    CLIENT_NAME VARCHAR(200),
    INDUSTRY VARCHAR(100),
    STATUS VARCHAR(50),
    IS_ACTIVE BOOLEAN,
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    COUNTRY VARCHAR(100),
    EMAIL VARCHAR(200),
    PHONE VARCHAR(50),
    SILVER_PROCESSED_AT TIMESTAMP_NTZ,
    SILVER_IS_CURRENT BOOLEAN
) COMMENT = 'Cleaned client data';

-- VENDORS
CREATE TABLE IF NOT EXISTS CEIPAL_VENDORS (
    ID VARCHAR(100) NOT NULL PRIMARY KEY,
    VENDOR_CODE VARCHAR(50),
    VENDOR_NAME VARCHAR(200),
    VENDOR_TYPE VARCHAR(100),
    STATUS VARCHAR(50),
    IS_ACTIVE BOOLEAN,
    EMAIL VARCHAR(200),
    PHONE VARCHAR(50),
    SILVER_PROCESSED_AT TIMESTAMP_NTZ,
    SILVER_IS_CURRENT BOOLEAN
) COMMENT = 'Cleaned vendor data';

-- EXPENSES
CREATE TABLE IF NOT EXISTS CEIPAL_EXPENSES (
    ID VARCHAR(100) NOT NULL PRIMARY KEY,
    EXPENSE_CODE VARCHAR(50),
    EMPLOYEE_ID VARCHAR(100),
    EMPLOYEE_NAME VARCHAR(200),
    PROJECT_ID VARCHAR(100),
    PROJECT_NAME VARCHAR(200),
    EXPENSE_TYPE VARCHAR(100),
    CATEGORY VARCHAR(100),
    DESCRIPTION VARCHAR(500),
    EXPENSE_DATE TIMESTAMP_NTZ,
    AMOUNT FLOAT,
    CURRENCY VARCHAR(10),
    STATUS VARCHAR(50),
    IS_APPROVED BOOLEAN,
    IS_REIMBURSED BOOLEAN,
    SILVER_PROCESSED_AT TIMESTAMP_NTZ,
    SILVER_IS_CURRENT BOOLEAN
) COMMENT = 'Cleaned expense data';

-- INVOICES
CREATE TABLE IF NOT EXISTS CEIPAL_INVOICES (
    ID VARCHAR(100) NOT NULL PRIMARY KEY,
    INVOICE_NUMBER VARCHAR(100),
    CLIENT_ID VARCHAR(100),
    CLIENT_NAME VARCHAR(200),
    PROJECT_ID VARCHAR(100),
    PROJECT_NAME VARCHAR(200),
    INVOICE_DATE TIMESTAMP_NTZ,
    DUE_DATE TIMESTAMP_NTZ,
    SUBTOTAL FLOAT,
    TAX FLOAT,
    TOTAL_AMOUNT FLOAT,
    CURRENCY VARCHAR(10),
    STATUS VARCHAR(50),
    IS_PAID BOOLEAN,
    IS_OVERDUE BOOLEAN,
    PAYMENT_DATE TIMESTAMP_NTZ,
    SILVER_PROCESSED_AT TIMESTAMP_NTZ,
    SILVER_IS_CURRENT BOOLEAN
) COMMENT = 'Cleaned invoice data';

-- Show all Silver tables
SHOW TABLES IN SCHEMA SILVER;
